apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.20-alpine3.12
          args:
            [
              "-p",   # port
              "4222",
              "-m",   # monitor
              "8222",
              "-hbi",
              "5s",
              "-hbt",
              "5s",
              "-hbf",
              "2",
              "-SD",
              "-cid",  # clusterID
              "products",
            ]
          env:
            - name: PGHOST
              value: "nats-cluster-ip:5432/nats"
            - name: JWT_KEY
              value: "jeff"
