apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false # don't push images to docker hub after skaffold builds them
  artifacts:
    # - image: cstudent/auth # build this image
    #   context: ./app/auth # from this directory
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts" # please watch these files
    #         dest: . # sync these files to the current directory of the running container
    # - image: cstudent/client
    #   context: ./app/client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     infer: # I had to sync things differently for vite-reload to work properly
    #       - "**/*.ts"
    #       - "**/*.vue"
    #       - "**/*.scss"
    #       - "**/*.css"
    # - image: cstudent/products
    #   context: ./app/products
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    - image: cstudent/kafka-kraft
      context: ./k8s/kafka/docker
      docker:
        dockerfile: Dockerfile
    # - image: cstudent/orders
    #   context: ./app/orders
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: cstudent/expiration
    #   context: ./app/expiration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: cstudent/payments
    #   context: ./app/payments
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
deploy:
  kubectl:
    manifests: # build components from these files
      # - ./k8s/auth/templates/*
      # - ./k8s/client/templates/*
      # - ./k8s/expiration/templates/*
      # - ./k8s/nats/templates/*
      - ./k8s/kafka/templates/*
      # - ./k8s/orders/templates/*
      # - ./k8s/payments/templates/*
      # - ./k8s/products/templates/*
# deploy:
#   helm:
#     releases:
#       - name: microservices-helm
#         namespace: default
#         recreatePods: true
#         chartPath: ../k8s/helm/microservices/
#         skipBuildDependencies: true
#         artifactOverrides:
#           auth:
#             image: cstudent/microservices-auth
#         imageStrategy:
#           helm: {}
