apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests: # build components from these files
      - ./k8s/auth/templates/*
build:
  local:
    push: false # don't push images to docker hub after skaffold builds them
  artifacts:
    - image: cstudent/auth # build this image
      context: ./app/auth # from this directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" # please watch these files
            dest: . # sync these files to the current directory of the running container
# deploy:
#   helm:
#     releases:
#       - name: microservices-helm
#         namespace: default
#         recreatePods: true
#         chartPath: ../k8s/helm/microservices/
#         skipBuildDependencies: true
#         artifactOverrides:
#           auth:
#             image: cstudent/microservices-auth
#         imageStrategy:
#           helm: {}
