apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false # don't push images to docker hub after skaffold builds them
    concurrency: 0
  artifacts:
    - image: cstudent/auth # build this image
      context: ./app/auth # from this directory
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts" # please watch these files
            dest: . # sync these files to the current directory of the running container
    - image: cstudent/client
      context: ./app/client
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer: # I had to sync things differently for vite-reload to work properly
          - "**/*.ts"
          - "**/*.vue"
          - "**/*.scss"
          - "**/*.css"
    - image: cstudent/expiration
      context: ./app/expiration
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cstudent/orders
      context: ./app/orders
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cstudent/payments
      context: ./app/payments
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cstudent/products
      context: ./app/products
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: cstudent/kafka-kraft
    #   context: ./weibuddies-iac/k8s/kafka/
    #   docker:
    #     dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./weibuddies-iac/k8s/_secrets/development.yaml
      - ./weibuddies-iac/k8s/services/*
      - ./weibuddies-iac/k8s/kafka/development.yaml
      - ./weibuddies-iac/k8s/ingress-config.yaml
profiles:
  - name: production
    deploy:
      kubectl:
        manifests:
          - ./weibuddies-iac/k8s/kafka/production.yaml
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: prod
      - op: replace
        path: /build/artifacts/1/docker/target
        value: prod
      - op: replace
        path: /build/artifacts/2/docker/target
        value: prod
      - op: replace
        path: /build/artifacts/3/docker/target
        value: prod
      - op: replace
        path: /build/artifacts/4/docker/target
        value: prod
      - op: replace
        path: /build/artifacts/5/docker/target
        value: prod
