apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-postgres
  template:
    metadata:
      labels:
        app: payments-postgres
    spec:
      containers:
        - name: payments-postgres
          image: postgres:14
