apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: cstudent/orders
          env:
            - name: PGHOST
              value: "orders-postgres-cluster-ip"
            - name: PGUSER
              value: "orders"
            - name: PGDATABASE
              value: "orders-database"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: JWT_KEY
            - name: KAFKA_ADVERTISED_LISTENERS
              value: kafka-0.kafka-svc.kafka-kraft.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: orders-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
### DATABASE ###
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: orders-postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "orders-database"
            - name: POSTGRES_USER
              value: "orders"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
--- 
apiVersion: v1
kind: Service
metadata:
  name: orders-postgres-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: orders-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432