apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: cstudent/payments
          env:
            - name: PGHOST
              value: "payments-postgres-cluster-ip"
            - name: PGUSER
              value: "payments"
            - name: PGDATABASE
              value: "payments-database"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: STRIPE_KEY
            - name: KAFKA_ADVERTISED_LISTENERS
              value: kafka-0.kafka-svc.kafka-kraft.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: payments-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000

### DATABASE ###
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-postgres
  template:
    metadata:
      labels:
        app: payments-postgres
    spec:
      containers:
        - name: payments-postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: "payments"
            - name: POSTGRES_DB
              value: "payments-database"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
--- 
apiVersion: v1
kind: Service
metadata:
  name: payments-postgres-svc
spec:
  selector:
    app: payments-postgres
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017