apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: cstudent/products
          env:
            - name: PGHOST
              value: "products-postgres-cluster-ip"
            - name: PGDATABASE
              value: "products-database"
            - name: PGUSER
              value: "products"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: JWT_KEY
            - name: KAFKA_ADVERTISED_LISTENERS
              value: kafka-0.kafka-svc.kafka-kraft.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: products-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3000 # the port other pods use to talk to this service
      targetPort: 3000 # the port that this service uses to talk to its pods

### DATABASE ###
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-postgres
  template:
    metadata:
      labels:
        app: products-postgres
    spec:
      containers:
        - name: products-postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "products-database"
            - name: POSTGRES_USER
              value: "products"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: products-postgres-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: products-postgres
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017