apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: cstudent/payments
          env:
            - name: NATS_CLUSTER_ID
              value: "products"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-cluster-ip:4222"
            - name: PGHOST
              value: auth-postgres-cluster-ip
            - name: PGUSER
              value: "payments"
            - name: PGDATABASE
              value: "payments-database"
            - name: PGPASSWORD
              value: "jeff"
            - name: JWT_KEY
              value: "jeff"
            - name: STRIPE_KEY
              value: "jeff"
              # valueFrom:
              #   secretKeyRef:
              #     name: stripe-secret
              #     key: STRIPE_KEY
