apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: cstudent/payments
          env:
            - name: PGHOST
              value: auth-postgres-cluster-ip
            - name: PGUSER
              value: "payments"
            - name: PGDATABASE
              value: "payments-database"
            - name: PGPASSWORD
              value: "jeff"
            - name: JWT_KEY
              value: "jeff"
            - name: STRIPE_KEY
              value: "jeff"
              # valueFrom:
              #   secretKeyRef:
              #     name: stripe-secret
              #     key: STRIPE_KEY
