apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: cstudent/orders
          env:
            - name: PGHOST
              value: orders-postgres-cluster-ip
            - name: PGUSER
              value: "orders"
            - name: PGDATABASE
              value: "orders-database"
            - name: PGPASSWORD
              value: "jeff"
            - name: JWT_KEY
              value: "jeff"
            - name: NATS_CLUSTER_ID
              value: "products"
            - name: NATS_URL
              value: "http://nats-cluster-ip:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
